### ISSUE TITLE
Unable to add integration

### ISSUE THREAD

**Issue by Hil333** [custom-components/nordpool#291] opened 2023-02-07 07:51 UTC
## Version of the custom_component
0.0.11

## Homeassistant version
2023.2.2

## Describe the bug
Unable to add integration, when adding it gives error: Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

## Debug log

Logger: homeassistant.util.package
Source: util/package.py:100
First occurred: 09:28:35 (3 occurrences)
Last logged: 09:28:38

Unable to install package nordpool>=0.2: Traceback (most recent call last): File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/usr/local/lib/python3.10/site-packages/pip/__main__.py", line 29, in <module> from pip._internal.cli.main import main as _main File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 9, in <module> from pip._internal.cli.autocompletion import autocomplete File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module> from pip._internal.cli.main_parser import create_main_parser File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/main_parser.py", line 9, in <module> from pip._internal.build_env import get_runnable_pip File "/usr/local/lib/python3.10/site-packages/pip/_internal/build_env.py", line 20, in <module> from pip._internal.cli.spinners import open_spinner File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/spinners.py", line 9, in <module> from pip._internal.utils.logging import get_indentation File "/usr/local/lib/python3.10/site-packages/pip/_internal/utils/logging.py", line 29, in <module> from pip._internal.utils.misc import ensure_dir File "/usr/local/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 41, in <module> from pip._internal.exceptions import CommandError File "/usr/local/lib/python3.10/site-packages/pip/_internal/exceptions.py", line 13, in <module> from pip._vendor.requests.models import Request, Response File "/usr/local/lib/python3.10/site-packages/pip/_vendor/requests/__init__.py", line 162, in <module> from .api import delete, get, head, options, patch, post, put, request File "/usr/local/lib/python3.10/site-packages/pip/_vendor/requests/api.py", line 11, in <module> from . import sessions File "/usr/local/lib/python3.10/site-packages/pip/_vendor/requests/sessions.py", line 15, in <module> from .adapters import HTTPAdapter File "<frozen importlib._bootstrap>", line 1027, in _find_and_load File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 688, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 879, in exec_module File "<frozen importlib._bootstrap_external>", line 1012, in get_code File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode SystemError: Objects/codeobject.c:141: bad argument to internal function

```

**Comment by t0xa** [comment] 2023-02-11 18:46
Hello @Hil333 

I've recently installed this integration on two different HA instances and it worked well. 
Could you please post full log file.

Thx

**Comment by Hil333** [comment] 2023-02-11 22:00
> Hello @Hil333
> 
> I've recently installed this integration on two different HA instances and it worked well. Could you please post full log file.
> 
> Thx

[home-assistant_2023-02-11T21-58-35.553Z.log](https://github.com/custom-components/nordpool/files/10714803/home-assistant_2023-02-11T21-58-35.553Z.log)

**Comment by t0xa** [comment] 2023-02-12 18:35
The root cause is very strange - `homeassistant.requirements.RequirementsNotFound: Requirements for nordpool not found: ['nordpool>=0.2'].`

The latest version is `0.0.11`. 

Follow-up questions:
 * How does the HACS install dialog looks like? On my instance it looks like this:
 
<img width="603" alt="image" src="https://user-images.githubusercontent.com/3533/218329921-8a624512-27de-493f-b29a-a5dc78e9d6e1.png">
 
 * Could you try the manual installation method?
 * Can you install any other custom component via HACS? For example: "Average Sensor"?

**Comment by t0xa** [comment] 2023-02-13 12:43
Sorry I confused nordpool python library with the nordpool custom component. 

In any case the root cause is that your system somehow couldn't install dependencies.

Follow-up questions:
- Could you try the manual installation method?
- Can you install any other custom component via HACS? For example: "Average Sensor"?

**Comment by Hil333** [comment] 2023-02-14 08:56
Manual installation doesn't work either and I have another custom componets from HACS and they works. I also installed Average Sensor and got it working too

**Comment by Hellowlol** [comment] 2023-03-26 19:30
Closing this issue as its unrelated to this integration

**Closed by Hellowlol** 2023-03-26 19:30 UTC
