### ISSUE TITLE
Suddenly nordpool integration stop updating at midnight

### ISSUE THREAD

**Issue by sevrinrobstad** [custom-components/nordpool#124] opened 2022-03-18 07:54 UTC
Two nights in a row now, the nordpool integration have stopped working for me at the same time (23:00).

![image](https://user-images.githubusercontent.com/23063479/158958630-9dc19e0d-c79f-4efd-bd09-e6fe19b56818.png)

It can be fixed by reloading the integration, but it seems that it only imports todays values, not tomorrows values, and also it doesn't automatically reload them.
this is after reload:
![image](https://user-images.githubusercontent.com/23063479/158959270-fc289326-a12b-479d-96c2-d5a2895f5a5f.png)

Running latest version and latest home assistant container.

**Comment by Hellowlol** [comment] 2022-03-18 08:19
Do you have multiple nordpool sensors? 

Do you have a debug log you can share?

The reason why we don't have data for tomorrow is because tomorrow's price data isn't available yet.

Example:
The time is 00:01, you reload the nordpool sensor/restart homeassistant. The time is not 00:03, the integration will fetch todays prices, but tomorrow's will not be available until later as the prices for the next day isnt public until 13:00ish.

**Comment by svenlange2** [comment] 2022-03-18 09:18
Same problem. I am not interested in tomorrows data so much as for the fact that it must not stop. I expected at least after midnight the data for the upcoming day to be there but nothing showed up even in the next morning until I restarted HASS server. Something is clearly wrong.

**Comment by svenlange2** [comment] 2022-03-18 11:49
I might know what the problem is. Norpool sends as it seems data only for today and for the first hour of next day. Now the code seems to handle it so that as it receives this data at 13:00, that it thinks OK i have todays data and also tomorrows data. It does not really check that only one hour is present from tomorrows data. Next when the day changes it just presumes that this lacking data is ok for tomorrow and delivers that throgh the sensor. The next update will not happen before 13:00 next day and till then you have no data basically. This all comes down to the fact that Nordpool just is not sending tomorrows data for free more for the next day at all. Basic fix should be to actually fetch data at midnight between 00:00 and 01:00 to get the relevant data.

**Comment by sevrinrobstad** [comment] 2022-03-18 12:07
Aha, but that means that something have changed the last few days in regards to what data nordpool sends (when), or when the nordpool integration fetches data ?

**Comment by svenlange2** [comment] 2022-03-18 12:15
The integration has been programmed to fetch at 13:00 Swedish time. I think this has been around for some time. Only my wild guess is that Nordpool tries to get more money from the service. For now it seems that if they provide only one hour in advance for next day then all people relying on it can still run automations when they fetch shortly after midnight. They just cannot do automations which need more advanced price data. You just dont have the luxury of predetermining things more ahead without money. Id imagine that all these small startups providing Nordpool data based wall switches now have to either pay money or somehow manage to propagate all info to their clients within one hour after midnight (quite challenging i guess) ;)

**Comment by Boggie** [comment] 2022-03-18 12:23
I think I saw something sometimes about nordpools day-ahead api was being shut down mid March, which fits with the time. It was supposed to be replaced by "the auction api". I have tried googling for the news article, but can't find it anywhere :(

I found an android app that works for danish prices (DK1), and before 13:00 it shows only todays prices, but 20 minutes ago, at 13:00, I can see the prices for tomorrow. So the data is still out there, but might have moved. I have no idea where the app gets its data.

**Comment by Hellowlol** [comment] 2022-03-18 12:44
I believe the there is a bug somewhere, but i don't know where :P. I'll see if i can recreate the issue while i have debug logging on.

**Comment by Zkaning** [comment] 2022-03-18 12:44
Same issue here.

**Comment by Reidar6** [comment] 2022-03-18 13:18
Same here, and most likely depending on the API replacement. 

https://developers.nordpoolgroup.com/docs/da-introduction

**Comment by Hellowlol** [comment] 2022-03-18 13:37
If the access gets restricted behind a paywall i'll make a new integration using entsoe. I have already verified that it works, the only downside is that the prices are in EUR.

**Comment by Hellowlol** [comment] 2022-03-18 13:37
If anybody have logs that they can post i'll appreciate it :)

**Comment by Skeletorjus** [comment] 2022-03-18 13:52
In my case a restart of Home Assistant brings in all of tommorow's prices.

**Comment by jonasbkarlsson** [comment] 2022-03-18 15:22
A restart of HA brings back tomorrow's prices for me as well. 

Is this how to enable debug information?
```
logger:
  default: warning
    nordpool: debug

```

**Comment by svenlange2** [comment] 2022-03-18 15:52
Never mind my comment. I dont know what is going on. Now the fetch apparently has worked. It got full tomorrows data again in HASS.

**Comment by yozik04** [comment] 2022-03-18 17:24
yesterday looks like there was a glitch and data was not fetched. I could not find any debug info in the log. Strange that no retry was triggered.

**Comment by MTrab** [comment] 2022-03-18 18:56
> If the access gets restricted behind a paywall i'll make a new integration using entsoe. I have already verified that it works, the only downside is that the prices are in EUR.

EUR should be easy to handle ;)

**Comment by peternorlander** [comment] 2022-03-18 19:02
I really like this integration, thanks! But I'm also suffering from the same problem. Started yesterday for me. A reload of the integration does nothing but a restart of HA works.

**Comment by gulli1986** [comment] 2022-03-18 19:07
Same for me, started yesterday, only restart of HA helps.

**Comment by Hellowlol** [comment] 2022-03-18 19:17
Reload should work if you have setup the sensor using the UI and only have one nordpool sensor.

**Comment by peternorlander** [comment] 2022-03-18 19:33
> Reload should work if you have setup the sensor using the UI and only have one nordpool sensor.

Oh, sorry, yes it was setup using yml. I have removed that to setup using the UI instead now. Have also enabled debug logging so I hope to be able to provide some good logging for tomorrow. Because now after the restart the prices are all there.

**Comment by Hellowlol** [comment] 2022-03-18 19:55
Looking at the logs it seems that the api didnt return any values when its did the api call at

```
2022-03-17 13:08:47 DEBUG (MainThread) [custom_components.nordpool] Called new_data_cb
2022-03-17 13:08:47 DEBUG (MainThread) [custom_components.nordpool] Updating tomorrows prices.
2022-03-17 13:08:47 DEBUG (MainThread) [custom_components.nordpool] calling _update tomorrow 2022-03-18 13:08:47.001904+01:00
2022-03-17 13:08:47 DEBUG (MainThread) [custom_components.nordpool.aio_price] requested https://www.nordpoolgroup.com/api/marketdata/page/10?currency=NOK&endDate=18-03-2022 {'currency': 'NOK', 'endDate': '18-03-2022'}

This returned the data (Thist is just a snip from my own zone):
'Kr.sand': {'Min': inf, 'Max': inf, 'Average': inf, 'Peak': inf, 'Off-peak 1': inf, 'Off-peak 2': inf, 'values': [{'start': datetime.datetime(2022, 3, 16, 23, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 0, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 0, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 1, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 1, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 2, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 2, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 3, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 3, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 4, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 4, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 5, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 5, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 6, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 6, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 7, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 7, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 8, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 8, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 9, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 9, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 10, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 10, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 11, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 11, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 12, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 12, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 13, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 13, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 14, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 14, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 15, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 15, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 16, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 16, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 17, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 17, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 18, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 18, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 19, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 19, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 20, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 20, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 21, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 21, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 22, 0, tzinfo=<UTC>), 'value': inf}, {'start': datetime.datetime(2022, 3, 17, 22, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 17, 23, 0, tzinfo=<UTC>), 'value': inf}]},

Later this blows up with a exception as all the values are inf, and the sensor is basically stuck there.

Traceback (most recent call last):
  File "/config/custom_components/nordpool/sensor.py", line 460, in check_stuff
    self._update(self._data_today)
  File "/config/custom_components/nordpool/sensor.py", line 314, in _update
    self._peak = mean(peak)
  File "/usr/local/lib/python3.9/statistics.py", line 316, in mean
    T, total, count = _sum(data)
  File "/usr/local/lib/python3.9/statistics.py", line 166, in _sum
    for n, d in map(_exact_ratio, values):
  File "/usr/local/lib/python3.9/statistics.py", line 248, in _exact_ratio
    raise TypeError(msg.format(type(x).__name__))
TypeError: can't convert type 'NoneType' to numerator/denominator
```

I suspect they had issues with the data and didn't release then at the normal time. This could be fixed by pulling the data later and/or if by verifying that the correct data is there and retry later if it isn't.

**Comment by peternorlander** [comment] 2022-03-18 20:10
Ok, so you know what to do? I don't need to gather any additional logs? :)

**Comment by Hellowlol** [comment] 2022-03-18 20:34
Yeah, i think so. I guess we will see next time the api returns inf value

**Comment by mickejo** [comment] 2022-03-19 06:49
I looked at the webpage just after 13.00. There were prices in EUR, but not in the other currencies, those were published approximately 15-20min later.

**Comment by peternorlander** [comment] 2022-03-19 14:23
Hi! Ok, here is the log file from a couple of hours today. It is as you said, we appear to receive junk from the api. But if I reloaded the integration (note in the log when that was triggered) everything is loadad as it should.  Does this help?

[nordpool log.txt](https://github.com/custom-components/nordpool/files/8309390/nordpool.log.txt)

I'm also attaching a screenshot of the history of the sensor and something has happened with it after I moved the setup yesterday evening from yml to UI. Do you see that the price drops for about one second at every hour when the price changes. It always drops to 0,35 SEK/kWh. 
![Screenshot_2022-03-19-11-03-30-06_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/1375002/159124809-cb971198-665c-4dbb-9a48-1b53f4af237e.jpg)

**Comment by peternorlander** [comment] 2022-03-20 12:07
I reloaded the integration just now at 13:05 and then the correct values where added.

**Comment by bj00rn** [comment] 2022-03-20 15:13
Same issue here! Not getting any values. Reloading the integration solves the problem. Not seeing any errors in logs.

**Comment by kpoppel** [comment] 2022-03-20 15:55
I can confirm the issue as well.  Problem is described in log like this:
```
Logger: homeassistant.util.logging
Source: util/logging.py:105
First occurred: 18. marts 2022 00.00.00 (71 occurrences)
Last logged: 16.00.00

Exception in check_stuff when dispatching 'nordpool_update': () Traceback (most recent call last): File "/config/custom_components/nordpool/sensor.py", line 460, in check_stuff self._update(self._data_today) File "/config/custom_components/nordpool/sensor.py", line 314, in _update self._peak = mean(peak) File "/usr/local/lib/python3.9/statistics.py", line 316, in mean T, total, count = _sum(data) File "/usr/local/lib/python3.9/statistics.py", line 166, in _sum for n, d in map(_exact_ratio, values): File "/usr/local/lib/python3.9/statistics.py", line 248, in _exact_ratio raise TypeError(msg.format(type(x).__name__)) TypeError: can't convert type 'NoneType' to numerator/denominator
```

Looks like the data returned from Nordpool is not as expected.  Note the first occurrence matches the original reporter too.

**Comment by Hellowlol** [comment] 2022-03-20 18:18
I have made a branch that I think should fix this issue. However, I'll leave it running for a couple of days to see that it's working as intended.

If anybody wants to test https://github.com/custom-components/nordpool/tree/fix-1 it would be much appreciated 😊

**Comment by kjbu** [comment] 2022-03-20 20:35
@Hellowlol , has this error nothing to do with the statement from NordPool saying that the API will be discontinued 15. March? : https://developers.nordpoolgroup.com/docs/da-introduction?fbclid=IwAR1ibGErGfykbqXbhyz834AIUdhtXx8w7iU6Cgu6m9Rgjmn9P2TwTjY1v64

_"IMPORTANT: The Nord Pool Day Ahead XML API is planned to be discontinued following March 15th. It will be replaced with the Auction API, currently in use in our Central Western European markets, Poland and United Kingdom."_

**Comment by Hellowlol** [comment] 2022-03-20 21:29
@kjbu the site still uses the old api so it should be unrelated. It might break down anytime tho 😁

**Comment by oivindklausen** [comment] 2022-03-20 21:59
@Hellowlol  Any plans to make a similar Entso based Sensor ?

**Comment by Hellowlol** [comment] 2022-03-20 23:40
When it breaks yes.

**Comment by gfrancesco** [comment] 2022-03-21 13:40
Just wanted to comment that I had the same issue last week, but yesterday and today the sensor started working again. Right now I can see the prices for tomorrow.
Didn't change anything except maybe updating home assistant a couple of days ago.

**Comment by Leatherface75** [comment] 2022-03-21 13:47
> Just wanted to comment that I had the same issue last week, but yesterday and today the sensor started working again. Right now I can see the prices for tomorrow. Didn't change anything except maybe updating home assistant a couple of days ago.

Probably it was caused by late reporting. It works here again too.

**Comment by Hellowlol** [comment] 2022-03-21 14:43
That’s great news @guni12. Let me know if you have any issues when the prices for the 23 is released.

**Comment by guni12** [comment] 2022-03-21 15:26
@Hellowlol, will do :-)

**Comment by jesperll** [comment] 2022-03-21 18:29
My installation also just started to work again on its own.

In the meantime I stumbled across a post on the Danish site version2.dk about a Danish site that also exposes the data (in EUR and DKK): 
https://www.version2.dk/holdning/hvad-koster-stroemmen
https://www.energidataservice.dk/guides/api-guides

As an example data for the next 48 hours in the DK2 zone can be fetched using https://api.energidataservice.dk/datastore_search?resource_id=elspotprices&limit=48&filters={%22PriceArea%22:%22DK2%22}&sort=HourUTC%20desc

Here 's a gist with some code also linked from that article:
https://gist.github.com/tiede/66a160f8361e0821b904c6d47c6c7d71

If nordpool restricts their API it'll be beneficial to have multiple other data providers to fall back on

**Comment by MTrab** [comment] 2022-03-21 18:37
@jesperll - I'm actually working on that integration right now :)

**Comment by erikbjork** [comment] 2022-03-21 19:43
Nordpool service status page says there were problems with the "Day Ahead Web" on March 16 & 17: https://developers.nordpoolgroup.com/docs/service-status

**Comment by alexschwantes** [comment] 2022-03-21 20:54
> I have made a branch that I think should fix this issue. However, I'll leave it running for a couple of days to see that it's working as intended.
> 
> If anybody wants to test https://github.com/custom-components/nordpool/tree/fix-1 it would be much appreciated 😊

@Hellowlol - I had a quick look at the PR and I think this is going in the right direction, as it is working to fix the tomorrow_valid flag raised from #82 and actually check if the values are valid, and if not to try again at a later date (+5 minutes).

I would throw in a little question, is 5 minutes is a suitable timeframe to retry? If their service goes down for a couple days (as it looks like was the recent issue) it would spam them pretty heavily. You could implement an incremental backoff retry time, or maybe the easiest is to just check every hour (like at the next scheduled update)?

keep up the good work!

**Comment by yozik04** [comment] 2022-03-21 21:06
Good practice is to randomize retry time and exponentially make retry period longer again with randomization involved.

**Comment by Hellowlol** [comment] 2022-03-21 22:14
@alexschwantes and @yozik04 You both have valid points, do you have any additional comments regarding the PR. Please comments in on the PR :)

**Comment by guni12** [comment] 2022-03-22 18:01
@Hellowlol, sorry for late reply, but yes, it worked today also. Thanks again for working with this. Your integration is such a great help, especially now when prices fluctuate so much.

**Comment by Inrego** [comment] 2022-03-29 18:16
> My installation also just started to work again on its own.
> 
> In the meantime I stumbled across a post on the Danish site version2.dk about a Danish site that also exposes the data (in EUR and DKK): 
> https://www.version2.dk/holdning/hvad-koster-stroemmen
> https://www.energidataservice.dk/guides/api-guides
> 
> As an example data for the next 48 hours in the DK2 zone can be fetched using https://api.energidataservice.dk/datastore_search?resource_id=elspotprices&limit=48&filters={%22PriceArea%22:%22DK2%22}&sort=HourUTC%20desc
> 
> Here 's a gist with some code also linked from that article:
> https://gist.github.com/tiede/66a160f8361e0821b904c6d47c6c7d71
> 
> If nordpool restricts their API it'll be beneficial to have multiple other data providers to fall back on

It seems that data will not be updated during weekends or public holidays:
https://www.energidataservice.dk/tso-electricity/elspotprices

**Comment by kjbu** [comment] 2022-03-31 18:29
Yea, would be a great idea if the integration had several sources to retrieve the prices from. If the primary fails, go to the next provider. If the 2nd provider fails, go to the 3rd, and so on. 
When providers stop sharing the prices, include new sources in the list of hourly price-providers.

@Hellowlol: Maybe this is too complicated for a 1-man-homemade-integration? ;-)

**Comment by gfrancesco** [comment] 2022-03-31 18:48
> @Hellowlol, today my not updated integrations needed restart, while the updated one showed todays values for tomorrow as well. Log: Platform nordpool does not generate unique IDs. ID nordpool_kwh_se3_sek_4_10_0 already exists - ignoring sensor.nordpool_kwh_se3_sek_4_10_0 Perhaps has something to do with it?

Same here, today didn't update either and needed a restart.

**Comment by Hellowlol** [comment] 2022-03-31 19:19
@gfrancesco Just reload the sensor. I don’t know why ha want to add this as a new sensor, it isn’t..  is should be the same entity_id.

**Comment by gfrancesco** [comment] 2022-03-31 20:06
Sorry, could have spent a few more words..
I didn't check the logs if it was complaining about any entity_id change, I just restarted HA and tomorrows prices were there after restart. Today it didn't update by itself with tomorrow's prices as usual around 13-14.
The same happened a couple of days ago.

**Comment by LordMike** [comment] 2022-04-01 08:03
I'm continuously hit by this - I'm running the current stable/HACS install - so no branch/fix applied. I couldn't determine from the issue here if the actual bug has been identified or not. I've enabled debug logs for me, so I can contribute with that when they appear (around 13-ish I guess).

Status now is:
- I'm using the yaml config mode
- The integration loads data on HA restart
- The integration will sometimes load data for tomorrow
- The integration will often just not have any data, leading to a stuck sensor at some price

**Comment by yozik04** [comment] 2022-04-01 20:04
Why we need to query any data at midnight? We can just copy it from "tomorrows" data. Then we need just one successful request per day.

**Comment by Hellowlol** [comment] 2022-04-01 20:13
@LordMike debug logs would be very helpful and much appreciated!

**Comment by Hellowlol** [comment] 2022-04-01 20:14
@yozik04 with the current version we don’t, on the pr I have created, we do.

**Comment by yozik04** [comment] 2022-04-01 20:27
Your PR does not work now. Some functions are missing.

**Comment by nilrog** [comment] 2022-04-04 07:27
Any fix for this on the horizon? My nordpool sensor stopped working at midnight, again. I discovered last week that it was not working anymore so I restarted it, which brought it back to life for a couple of days.

**HA:** 2022.2.9
**Nordpool:** 0.0.4 (from HACS)

Same stacktrace as was posted 2 weeks ago above was found in the log.

```
2022-04-04 00:00:00 ERROR (MainThread) [homeassistant.util.logging] Exception in check_stuff when dispatching 'nordpool_update': ()
Traceback (most recent call last):
File "/config/custom_components/nordpool/sensor.py", line 460, in check_stuff
self._update(self._data_today)
File "/config/custom_components/nordpool/sensor.py", line 314, in _update
self._peak = mean(peak)
File "/usr/local/lib/python3.9/statistics.py", line 316, in mean
T, total, count = _sum(data)
File "/usr/local/lib/python3.9/statistics.py", line 166, in _sum
for n, d in map(_exact_ratio, values):
File "/usr/local/lib/python3.9/statistics.py", line 248, in _exact_ratio
raise TypeError(msg.format(type(x).__name__))
TypeError: can't convert type 'NoneType' to numerator/denominator
2022-04-04 00:00:00 ERROR (MainThread) [homeassistant.util.logging] Exception in check_stuff when dispatching 'nordpool_update': ()
Traceback (most recent call last):
File "/config/custom_components/nordpool/sensor.py", line 460, in check_stuff
self._update(self._data_today)
File "/config/custom_components/nordpool/sensor.py", line 314, in _update
self._peak = mean(peak)
File "/usr/local/lib/python3.9/statistics.py", line 316, in mean
T, total, count = _sum(data)
File "/usr/local/lib/python3.9/statistics.py", line 166, in _sum
for n, d in map(_exact_ratio, values):
File "/usr/local/lib/python3.9/statistics.py", line 248, in _exact_ratio
raise TypeError(msg.format(type(x).__name__))
TypeError: can't convert type 'NoneType' to numerator/denominator
```

**Comment by pinq-** [comment] 2022-04-13 16:26
So any news on this one? I can't get any data out of tihs

**Comment by pinq-** [comment] 2022-04-14 08:34
I just removed all the old nordpool components and reinstall it manually (UI Install didn't work for some reason), but I'm still getting null values: 
![image](https://user-images.githubusercontent.com/10464992/163346814-75c9c42a-3e94-4de5-9065-a09fb1084863.png)

**Comment by Hellowlol** [comment] 2022-04-14 08:59
Im gonna close and lock this issue as people are not keeping on topic. @pinq- open new issue using the template

**Closed by Hellowlol** 2022-04-14 08:59 UTC
Labels: bug, enhancement
