### ISSUE TITLE
Decimal precision not working after upgrade from 0.0.9 to 0.0.10

### ISSUE THREAD

**Issue by imfoffo** [custom-components/nordpool#271] opened 2023-01-09 22:48 UTC
Before the upgrade decimal precision was set to the value of 2 and the price was shown currently.
After upgrading to version 0.0.10 precision seems to be ignored, and the price is shown with 7 decimals. 
The upgrade is the only change.

From configuration.yaml

```
sensor:
  - platform: nordpool

    # Should the prices include vat? Default True
    VAT: True

    # What currency the api fetches the prices in
    # this is only need if you want a sensor in a non local currency
    currency: "DKK"

    # Option to show prices in cents (or the equivalent in local currency)
    price_in_cents: false

    # Helper so you can set your "low" price
    # low_price = hour_price < average * low_price_cutoff
    low_price_cutoff: 0.95

    # What power regions your are interested in.
    # Possible values: "DK1", "DK2", "FI", "LT", "LV", "Oslo", "Kr.sand", "Bergen", "Molde", "Tr.heim", "Tromsø", "SE1", "SE2", "SE3","SE4>
    region: "DK2"

    # How many decimals to use in the display of the price
    precision: 2

    # What the price should be displayed in default
    # Possible values: MWh, kWh and Wh
    # default: kWh
    price_type: kWh

    # This option allows the usage of a template to add a tariff.
    # now() always refers start of the hour of that price.
    # this way we can calculate the correct costs add that to graphs etc.
    # The price result of the additional_costs template expects this additional cost to be in kWh and not cents as a float
    # default {{0.0|float}}
    additional_costs: "{{1.59|float}}"
```

**Comment by KennethLavrsen** [comment] 2023-01-11 13:17
I am not a Python programmer - but I know enough Perl and C to read code

The issue is in sensor.py line 326

The developer made a mistake and changed the line 326 from return round(price, self._precision) to just return price

I did the fix in my installation

Just sensor.py line 326  - change it to

`return round(price, self._precision)`

**Comment by Hellowlol** [comment] 2023-01-11 20:46
This isn’t a bug. I removed the precision on purpose. Python round didn’t work the way I expected and it could create problems if the prices was low.

In hindsight maybe this was a premature action if people liked this functionality

**Comment by peternorlander** [comment] 2023-01-11 21:16
Hi, 
I also just did the update and I miss this feature. Maybe it could be configurable if it causes issues for others?

**Comment by KennethLavrsen** [comment] 2023-01-11 21:42
A price shown in the UI with 6 decimals is a bit silly. I would otherwise have to create a template sensor just to round the price off to something sensible.

**Comment by jenscski** [comment] 2023-01-12 07:55
@Hellowlol, is it possible to revert the change, and create a new sensor with e.g. _raw prefix (or something), which contains the "raw" value without any rounding?

**Comment by asdasddffgthhjtreresf** [comment] 2023-01-14 07:28
`2023-01-14 05:00:00.506 ERROR (MainThread) [homeassistant.util.logging] Exception in check_stuff when dispatching 'nordpool_update': ()
Traceback (most recent call last):
  File "/config/custom_components/nordpool/sensor.py", line 510, in check_stuff
    self._update()
  File "/config/custom_components/nordpool/sensor.py", line 336, in _update
    self._average = mean(today)
  File "/usr/local/lib/python3.10/statistics.py", line 329, in mean
    T, total, count = _sum(data)
  File "/usr/local/lib/python3.10/statistics.py", line 187, in _sum
    T = _coerce(T, typ)  # or raise TypeError
  File "/usr/local/lib/python3.10/statistics.py", line 237, in _coerce
    raise TypeError(msg % (T.__name__, S.__name__))
TypeError: don't know how to coerce float and NoneType

2023-01-14 05:00:00.513 ERROR (MainThread) [homeassistant.util.logging] Exception in check_stuff when dispatching 'nordpool_update': ()
Traceback (most recent call last):
  File "/config/custom_components/nordpool/sensor.py", line 510, in check_stuff
    self._update()
  File "/config/custom_components/nordpool/sensor.py", line 336, in _update
    self._average = mean(today)
  File "/usr/local/lib/python3.10/statistics.py", line 329, in mean
    T, total, count = _sum(data)
  File "/usr/local/lib/python3.10/statistics.py", line 187, in _sum
    T = _coerce(T, typ)  # or raise TypeError
  File "/usr/local/lib/python3.10/statistics.py", line 237, in _coerce
    raise TypeError(msg % (T.__name__, S.__name__))
TypeError: don't know how to coerce float and NoneType`
Is this caused because of this same thing?
My homeassistant log is full of these and the integration is not working at all. No prices shown.
Before working integration and entity shows now:
"This entity is no longer being provided by the nordpool integration. If the entity is no longer in use, delete it in settings."

**Comment by Hellowlol** [comment] 2023-01-14 17:49
Closing this as as a reverted as the decimal change in the latest pre-release.

Unrelated errors are ignored. Please create you own issue

**Closed by Hellowlol** 2023-01-14 17:49 UTC
